package com.gybandi.approvalcrest.tools;

import java.io.File;

import org.apache.maven.plugins.annotations.Mojo;

/**
 * 
 * Cleans unused json files generated by the Approvalcrest matchers.
 * 
 * @author András Gyuró
 *
 */
@Mojo(name = "clean")
public class CleanerMojo extends AbstractApprovalcrestMojo {

	@Override
	protected void handleJsonFile(File file) {
		String fileName = file.getName();
		file.delete();
		getLog().info(fileName + " deleted.");
	}

}
