package com.gybandi.approvalcrest.tools;

import java.io.File;

import org.apache.maven.plugins.annotations.Mojo;

/**
 * 
 * Discovers and logs unused json files generated by the Approvalcrest matchers.
 * 
 * @author András Gyuró
 *
 */
@Mojo(name = "discover")
public class DiscoverMojo extends AbstractApprovalcrestMojo {

	@Override
	protected void handleJsonFile(File file) {
		getLog().info(file.getName() + " " + file.getAbsolutePath());

	}

}
